# Generated by Django 3.0.7 on 2020-11-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igposca', '0004_taged_data_cur_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='posca_point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
