# Generated by Django 3.0.7 on 2020-11-24 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igposca', '0005_posca_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taged_data',
            name='cur_url',
        ),
    ]
