# Generated by Django 3.0.7 on 2020-11-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igposca', '0006_remove_taged_data_cur_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='taged_data',
            name='page_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
